var images = ["Ul-D12gQYR4RKKtcqmqsDQ","uAhuDQSHVSXRCmP5eqHmGg","_vXXqJhvPKbhyMCDyFsA3Q", "A-3lBUJhPkAwqlFnIMW1hg", "xO6DsVNqMt9Tv1bVTe8UGA","5PBPwFgmu_HvQLMPda0qgg","J_KPdrHAbv7yngT43w0qrg","xLNC-Awp85IPj79OPg4fUg","AP9myH8OEMh0rtuvaRdrSg","W1s_IT_WlQ3myQ3GOpbUfQ","YG8pa7KP5LAwCX_Jhhw8fg","RGbdNKEVHf-GLj8BNp8tlg","3xxrrl04fsqF262pFDzHyg"];
var basemap = ["satellite"]
var project_title = "Exploring the World"
var project_subtitle = "A selection of beautiful Mapillary sequences from across the world"
var titles = ["Utah", "British Columbia", "California", "South Dakota", "Wyoming","California","Chile","New Zealand","Sri Lanka","Iceland","Georgia","South Africa","Nepal"]
var content = ["The capital city of Utah, Salt Lake City is situated at the foot of the Wasatch Mountains and the Great Salt Lake. The city is close to a variety of environments, ranging from alpine peaks to pine forest to red desert. It was also the host of the 2002 Winter Olympics, and is the center of the Church of Jesus Christ of Latter Day Saints. The Wasatch and Uinta mountain ranges are located on the city's eastern outskirts, while an expanse of desert, salt flats, and the Great Salt Lake lie to the east. Salt Lake City offers access to over a dozen national parks, including Canyonlands, Bryce Canyon, and Arches.",
"Known for its mountains and rain, Vancouver is a port city on the Pacific coast of Canada. It was named or British Admiral George Vancouver, who sailed along the coast in the late 1700s. Vancouver hosted the 2010 Winter Olympics, and is close by the world famous Whistler Mountain Resort.",
"Rolling green hills and satellite dishs on the horizon epitomize the clash of natural beauty and cutting edge technology in the Bay Area. Located east of Silicon Valley, this scene from the San Jose hills shows rare open space in a rapidly growing population center.",
"One of the last elevated areas before the foothills of the Rocky Mountains give way to the great plains, the Black Hills area of South Dakota is pristine and isolated. However, nearby Mount Rushmore is a major tourist destination, while the spirit of the West lives on just down the highway in the town of Deadwood.",
"Grand Teton National Park is famous for its jagged peaks, pristine lakes, and wild west spirit. Just outside the town of Jackson, Wyoming, this area is still covered with wilderness inhabited by moose, wolves, and grizzly bears. The nearby valley is referred to as Jackson Hole, which stands in stark contrast to the towering mountains. In winter, the region is a playground for snowmobilers and skiers, while summer offers hiking, climbing, and camping to the heart's desire.",
"One of the hottest and driest places on earth, California's Death Valley is both bleak and breathtaking. The arid mountains are full of color, with spiking summer temperatures and yet a wintertime chill. Bring plenty of water and watch out for snakes, but don't let the morbid name of this region discourage you from visiting and experiencing its beauty.",
"Among the great deserts of the world, Chile's Atacama desert is isolated and vast. The high elevation and volcanic landscape make for remarkable sights, as visitors can beat the heat while gazing at snowcapped peaks alongside the highway. The town of San Pedro de Atacama is the central settlement of the region, but civilization is still a faraway thing in this region that is located hours and hours away from Chile's capital of Santiago.",
"Grand fjords and towering peaks bring renown to the Southern Alps, the backbone of New Zealand's south island. Fjordlands National Park and Milford Sound are some of the most fmaous locations, but natural beauty is easy to come by around every bend and corner. The steep mountains start at sea level and quickly climb into the clouds, making for easy sightseeing from the bow of a boat.",
"Clear blue water, sun-drenched beaches, and lazy palm trees make the beaches of Sri Lanka's southern shores an alluring place to relax. Green vegetation runs right up to the coastline, and the weather is warm year round due to proximity to the equator. The area is also a haven for surfers who travel across the world to ride waves on the Indian Ocean. In addition, some of the largest lizards in the world scamper in and out of the jungle, sharing the beaches with tourists and locals alike.",
"The Westmann Islands off of Iceland's southern coast are a green, mountainous paradise lost. Ravaged by volcanoes in the recent past, the serene chain of islands is a quiet place to lay eyes upon beaches of black sand, green ridges, and herds of wandering sheep. Known for its fishing industry, the main town is a sleepy place nestled below stunning scenery. The ferry arrives and departs several times a day from the mainland, and may be worth skipping for an extra day exploring this little geological wonder.",
"The Georgian Military Highway meanders through the deep valleys of the Caucasus Mountains, forming the only link from Russia into Georgia. In winter, the highway is maintained despited heavy snow in order to facilitate cargo transit, as well as support ski traffic. In summer, the mountains turn vividly green and are home to hidden ruins and medieval towers leftover from times past. The mountain town of Stepantsminda is a worthy stop on any tour, offering panoramic views of the surrounding peaks.",
"Cape Town is well known for stunning beaches, rugged landscape, and perfect weather. Hiking above the city offers views of land and water alike, while the greenery is in no shortage. Table Mountain is one of the most prominant landmarks in the area, and many other similar high ridges are quickly accessed from the bustling city center.",
"The Himalayas are often inaccessible and unforgiving, but the view from an airplane can still offer a perspective on even the most remote parts of the mountain range. The area around Mount Everest is a true ceiling of the world, and requires several days of trekking or a bumpy flight to reach its inner depths. Glaciers, clouds, and solitude are some of the magnificent treasures of this high altitude corner of the globe."
]
